default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV.fetch("MYSQL_PASSWORD", "password") %>
  host: <%= ENV.fetch("DB_HOST", "db") %>
  port: 3306

development:
  <<: *default
  database: my_blog_api_development

test:
  <<: *default
  database: my_blog_api_test

production:
  primary: &primary_production
    <<: *default
    database: my_blog_api_production
    username: my_blog_api
    password: <%= ENV["MY_BLOG_API_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: my_blog_api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: my_blog_api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: my_blog_api_production_cable
    migrations_paths: db/cable_migrate
