source "https://rubygems.org"

gem "rails", "~> 8.0.1"
gem "mysql2", "~> 0.5"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
gem "rack-cors", "~> 2.0"
gem "devise_token_auth"
gem "devise"

# 開発環境用のgemをdevelopmentグループに移動
group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end

# 本番環境用のgemを分離
group :production do
  gem "solid_cache"
  gem "solid_queue"
  gem "solid_cable"
  gem "kamal", require: false
  gem "thruster", require: false
end
